#!/bin/bash
###############################################################################
# Compile and run haskell programs
# Syntax: hrun [program name]

set -e

runhaskell Setup configure --prefix=$HOME --user
runhaskell Setup build
runhaskell Setup install

# Execute command
$@

