#!/bin/bash
###############################################################################
# Installation script to link in shell scripts

set -e

if [ ! -n "${TOBIAS_CONF}" ]; then
    echo "Run <SCRIPT_HOME>/vars before executing this file"
    exit 1
fi

echo "Installing..."

ln -svf ${SCRIPT_HOME}/shell/portkill ${HOME_DIR}/Bin/portkill
ln -svf ${SCRIPT_HOME}/shell/mcflush ${HOME_DIR}/Bin/mcflush
ln -svf ${SCRIPT_HOME}/shell/hrun ${HOME_DIR}/Bin/hrun
